### ISSUE TITLE
x11/intrinsic.h no such file

### ISSUE THREAD

**Issue by billpage** [GabrielDosReis/open-axiom#1]
Error message during make: x11/intrinsic.h no such file
Apparently configure does not check for the libXt dependency.

**Comment by GabrielDosReis** [comment]
Brief question: on what platform is this?
PS: Nothing has changed in this check for the last 10 years, so I'm surprised we didn't discover it earlier.-------- Original message --------From: Bill Page notifications@github.com Date: 1/18/2016  3:58 PM  (GMT-06:00) To: GabrielDosReis/open-axiom open-axiom@noreply.github.com Subject: [open-axiom] x11/intrinsic.h no such file (#1) 
Error message during make: x11/intrinsic.h no such file

Apparently configure does not check for the libXt dependency.

**Comment by billpage** [comment]
Platform - OpenSuse Leap 42.1
Note: On this system I also had to install a newer version of automake than
provided by the distribution.

Bill.

**Comment by GabrielDosReis** [comment]
Thanks for the info!
I not am able to get hold onto an openSUSE box before a week.

-- Gaby
